# Generated by Django 4.1.2 on 2022-10-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_list_post_milk_post_recommended_post_smoothies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=20)),
            ],
        ),
    ]
